# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
        - task: CmdLine@2
          inputs:
            script: |
              echo $(Build.SourceVersion)
              versiontag=$(echo -n $(git describe $(Build.SourceVersion)))
        - task: CmdLine@2
          inputs:
            script: 'echo $(versiontag)'
        - task: Docker@2
          inputs:
            containerRegistry: 'DockerHub-mvlab02'
            repository: 'mvlab02/azjsdemo01'
            command: 'build'
            Dockerfile: '**/Dockerfile'
            tags: $(versiontag)
        - task: Docker@2
          inputs:
            containerRegistry: 'DockerHub-mvlab02'
            repository: 'mvlab02/azjsdemo01'
            command: 'push'
            tags: '$(versiontag)'