# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
        - task: CmdLine@2
          displayName: Get-Application-Version
          inputs:
            script: |
              echo $(Build.SourceVersion)
              versiontag="$(echo -n $(git describe $(Build.SourceVersion)))"
              echo "##vso[task.setvariable variable=tag]$versiontag"
        - task: Docker@2
          displayName: Build Docker Images
          inputs:
            containerRegistry: 'DockerHub-mvlab02'
            repository: 'mvlab02/azjsdemo01'
            command: 'build'
            Dockerfile: '**/Dockerfile'
            tags: '$(tag)'
        - task: Docker@2
          displayName: Push Docker image to Repository
          inputs:
            containerRegistry: 'DockerHub-mvlab02'
            repository: 'mvlab02/azjsdemo01'
            command: 'push'
            tags: '$(tag)'
        - task: CmdLine@2
          inputs:
            script: 'echo -n "$(tag)" >>$(Build.ArtifactStagingDirectory)/Version.txt'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'AppVersionInfo'
            publishLocation: 'Container'
        