apiVersion: v1
kind: Service
metadata:
  name: jsdemo01
  labels:
    name: jsdemo01
    type: static-js
spec:
  type: NodePort
  selector:
    app: jsdemo01
  ports:
      - port: 80
        nodePort: 30001
